### PR TITLE
Fastlane integration

### PR DESCRIPTION
**Pull request by fuzza**
Implements #4

### CODE REVIEW

**Comment by sergeyzenchenko** [comment]
BTW, I did some experiments in this direction https://github.com/techery/Tesla

**Comment by fuzza** [comment]
@sergeyzenchenko Thanks for your attention to the project. 
I looked at the code and it's very close to original Java implementation and at the same time uses some nice Swift features that is cool! 

Ideas behind it are a good starting point for SiwftyJanet and I'd greatly appreciate any help and involvement in this project from your side!

**Review by demalex — APPROVED** [review]
Looks good 👍🏻

**Comment by sergeyzenchenko** [comment]
@fuzza it was actually stupid reimplementation in swift almost class by class :D

**Pull request merged**
